export const PROCESS_HOME_DATA = 'HOME/ROCESS_HOME_DATA'
export const PROCESS_LOCAL_HOME_DATA = 'HOME/PROCESS_LOCAL_HOME_DAT'
export const GO_TO_IMG = 'HOME/GO_TO_IMG'
export const PROCESS_LOADING_DATA = 'HOME/PROCESS_LOADING_DATA'